version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
